from enum import Enum


class ArticleStatus(str, Enum):
    NEW = "NEW"
    FETCHED = "FETCHED"
    NORMALIZED = "NORMALIZED"
    RELEVANCE_PASSED = "RELEVANCE_PASSED"
    RELEVANCE_REJECTED = "RELEVANCE_REJECTED"
    DEDUP_PASSED = "DEDUP_PASSED"
    DEDUP_REJECTED = "DEDUP_REJECTED"
    COMPRESSED = "COMPRESSED"
    COMPRESS_FAILED = "COMPRESS_FAILED"
    INGESTED = "INGESTED"
    INGEST_FAILED = "INGEST_FAILED"

