#------------project configuration start----------------#
openie_llm: &openie_llm
  type: maas
  base_url: https://api.siliconflow.cn/v1
  api_key: sk-REDACTED
  model: Qwen/Qwen2.5-32B-Instruct
  enable_check: false

chat_llm:
  type: maas
  base_url: https://api.siliconflow.cn/v1
  api_key: sk-REDACTED
  model: Qwen/Qwen2.5-32B-Instruct
  enable_check: false

vectorize_model: &vectorize_model
  api_key: sk-REDACTED
  base_url: https://api.siliconflow.cn/v1
  model: Qwen/Qwen3-Embedding-8B
  type: openai
  vector_dimensions: 1024
  enable_check: false
vectorizer: *vectorize_model

log:
  level: INFO

project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '2'
  language: zh
  namespace: EnterpriseNewsCompanyOnly20260227
#------------project configuration end----------------#

#------------kag-builder configuration start----------------#
kag_builder_pipeline:
  chain:
    type: unstructured_builder_chain
    extractor:
      type: schema_constraint_extractor
      llm: *openie_llm
      ner_prompt:
        type: company_only_ner
      std_prompt:
        type: default_std
    reader:
      type: txt_reader
    post_processor:
      type: kag_post_processor
    splitter:
      type: length_splitter
      split_length: 2000
      window_length: 100
    vectorizer:
      type: batch_vectorizer
      vectorize_model: *vectorize_model
    writer:
      type: kg_writer
  num_threads_per_chain: 1
  num_chains: 4
  scanner:
    type: file_scanner
#------------kag-builder configuration end----------------#
