"""Catalog-only operator specs used by the knowledge computing workbench."""

from __future__ import annotations

from typing import Dict, List

from app.knowledge_extraction_operators.base import OperatorSpec


LAYER_DEFINITIONS: List[Dict[str, object]] = [
    {
        "key": "data_ingestion_loading",
        "name": "数据接入与加载",
        "description": "负责多源异构数据的接入、读取和源对象统一化，是知识计算全流程的入口层。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "data_preprocessing_structuring",
        "name": "数据预处理与结构化",
        "description": "负责文档解析、清洗、标准化、切块和表格结构化，把原始数据变成可抽取对象。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "knowledge_extraction",
        "name": "知识抽取",
        "description": "负责实体、关系、事件、概念和表格事实等知识单元抽取。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "knowledge_alignment_standardization",
        "name": "知识对齐与标准化",
        "description": "负责实体归一、术语标准化、编码对齐和概念挂载，把候选知识变成统一知识对象。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "knowledge_fusion_graph_build",
        "name": "知识融合与图构建",
        "description": "负责多源知识融合、子图组装、图谱批次构建与 OpenSPG 导入。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "knowledge_retrieval_recall",
        "name": "知识检索与召回",
        "description": "负责向量检索、图谱检索、混合检索和专题召回。",
        "operator_classes": ["general", "business"],
    },
    {
        "key": "reasoning_decision_generation",
        "name": "推理与决策生成",
        "description": "负责规则推理、多跳推理、评估、预警和报告生成。",
        "operator_classes": ["general", "business"],
    },
]


LAYER_TO_CATEGORY = {
    "source_ingest": "data_ingestion_loading",
    "document_parse": "data_preprocessing_structuring",
    "structure": "data_preprocessing_structuring",
    "extract": "knowledge_extraction",
    "mapping": "knowledge_fusion_graph_build",
    "fusion": "knowledge_fusion_graph_build",
}


BUSINESS_OPERATORS = {
    "event_enrich",
    "entity_resolve",
    "event_resolve",
    "concept_bind",
    "fusion_graph_build",
}


ALIGNMENT_OPERATORS = {
    "event_enrich",
    "entity_resolve",
    "event_resolve",
    "concept_bind",
}


def classify_operator(spec: OperatorSpec) -> tuple[str, str]:
    category = spec.knowledge_category or LAYER_TO_CATEGORY.get(
        spec.layer, "knowledge_fusion_graph_build"
    )
    operator_class = spec.operator_class or "general"

    if not spec.knowledge_category and spec.name in ALIGNMENT_OPERATORS:
        category = "knowledge_alignment_standardization"

    if not spec.operator_class and spec.name in BUSINESS_OPERATORS:
        operator_class = "business"

    return category, operator_class


PLANNED_OPERATOR_SPECS: List[OperatorSpec] = [
    OperatorSpec(
        name="pdf_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="接入本地或对象存储中的 PDF 文件，统一转成文档源记录。",
        input_type="PdfSourceDTO",
        output_type="DocumentSourceDTO",
        implementation_ref="planned:dataflow/pdf-source-adapter",
        applicable_sources=["report", "pdf"],
        tags=["source", "pdf", "ingest"],
        decoupling_reason="PDF 接入只依赖文件路径和基础元数据，可作为稳定入口复用于研报、公告和政策文档。",
    ),
    OperatorSpec(
        name="webpage_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="抓取网页正文和元数据，统一生成网页文档源记录。",
        input_type="WebPageSourceDTO",
        output_type="DocumentSourceDTO",
        implementation_ref="planned:dataflow/webpage-source-adapter",
        applicable_sources=["news", "webpage", "url"],
        tags=["source", "web", "ingest"],
        decoupling_reason="网页接入与后续实体/事件抽取解耦，任何 URL 类输入都可以复用这一步。",
    ),
    OperatorSpec(
        name="docx_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="接入 docx 文档并抽取正文和文档属性。",
        input_type="DocxSourceDTO",
        output_type="DocumentSourceDTO",
        implementation_ref="planned:dataflow/docx-source-adapter",
        applicable_sources=["report", "docx"],
        tags=["source", "docx", "ingest"],
        decoupling_reason="Word 文档的接入逻辑独立于知识抽取规则，适合抽成通用源适配器。",
    ),
    OperatorSpec(
        name="markdown_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="接入 Markdown 文本并保留标题、段落和引用结构。",
        input_type="MarkdownSourceDTO",
        output_type="DocumentSourceDTO",
        implementation_ref="planned:dataflow/markdown-source-adapter",
        applicable_sources=["markdown", "note", "report"],
        tags=["source", "markdown", "ingest"],
        decoupling_reason="Markdown 已是半结构化格式，接入可以和抽取逻辑完全分离。",
    ),
    OperatorSpec(
        name="rss_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="消费 RSS/Atom 订阅源并生成资讯源记录。",
        input_type="RssFeedDTO",
        output_type="DocumentSourceDTO",
        implementation_ref="planned:dataflow/rss-source-adapter",
        applicable_sources=["news", "rss"],
        tags=["source", "rss", "ingest"],
        decoupling_reason="资讯订阅接入是独立步骤，后续抽取可复用同一资讯处理链。",
    ),
    OperatorSpec(
        name="structured_table_source_ingest",
        stage="ingest",
        layer="source_ingest",
        status="planned",
        description="把结构化表或数仓行统一转成标准结构化源记录。",
        input_type="StructuredTableRowDTO",
        output_type="StructuredRowDTO",
        implementation_ref="planned:dataflow/structured-table-adapter",
        applicable_sources=["fact_table", "ods", "csv"],
        tags=["source", "table", "structured"],
        decoupling_reason="结构化行接入不依赖后续图谱 schema，可作为所有常识数据的统一入口。",
    ),
    OperatorSpec(
        name="pdf_parse",
        stage="parse",
        layer="document_parse",
        status="planned",
        description="把 PDF 文档解析成正文、页码和版面信息。",
        input_type="DocumentSourceDTO",
        output_type="DocumentDTO",
        implementation_ref="kag.reader.PDFReader",
        applicable_sources=["report", "pdf"],
        tags=["parse", "pdf", "document"],
        decoupling_reason="PDF 解析只关注版面到文本的转换，与下游实体/事件抽取无关。",
    ),
    OperatorSpec(
        name="html_extract",
        stage="parse",
        layer="document_parse",
        status="planned",
        description="从网页 HTML 中提取正文、标题和发布时间。",
        input_type="DocumentSourceDTO",
        output_type="DocumentDTO",
        implementation_ref="planned:dataflow/html-extract",
        applicable_sources=["news", "webpage", "url"],
        tags=["parse", "html", "document"],
        decoupling_reason="网页正文抽取是通用处理步骤，可服务资讯、公告和政策页面。",
    ),
    OperatorSpec(
        name="markdown_normalize",
        stage="parse",
        layer="document_parse",
        status="planned",
        description="规范 Markdown 结构、标题层级和引用块格式。",
        input_type="DocumentSourceDTO",
        output_type="DocumentDTO",
        implementation_ref="kag.reader.MarkDownReader",
        applicable_sources=["markdown", "report", "note"],
        tags=["parse", "markdown", "normalize"],
        decoupling_reason="Markdown 规范化只依赖文档结构本身，适合作为统一前置算子。",
    ),
    OperatorSpec(
        name="document_clean",
        stage="parse",
        layer="document_parse",
        status="planned",
        description="清理噪声字符、页眉页脚和多余空白，生成可抽取正文。",
        input_type="DocumentDTO",
        output_type="DocumentDTO",
        implementation_ref="planned:dataflow/text-clean",
        applicable_sources=["report", "news", "document"],
        tags=["parse", "clean", "normalize"],
        decoupling_reason="清洗规则与具体知识 schema 无关，适合复用成标准文档清理算子。",
    ),
    OperatorSpec(
        name="chunk_split",
        stage="structure",
        layer="structure",
        status="planned",
        description="按长度、语义或结构把文档拆成标准 chunk。",
        input_type="DocumentDTO",
        output_type="ChunkListDTO",
        implementation_ref="kag.splitter.LengthSplitter|SemanticSplitter|OutlineSplitter",
        applicable_sources=["report", "news", "document"],
        tags=["structure", "chunk", "split"],
        decoupling_reason="切块只依赖文档内容和分块策略，天然适合做成可配置算子。",
    ),
    OperatorSpec(
        name="outline_extract",
        stage="structure",
        layer="structure",
        status="planned",
        description="抽取章节结构，补充 section 和标题层级。",
        input_type="DocumentDTO",
        output_type="OutlineDTO",
        implementation_ref="kag.extractor.OutlineExtractor",
        applicable_sources=["report", "document"],
        tags=["structure", "outline", "section"],
        decoupling_reason="章节结构可被多个抽取任务复用，不应耦合到单一知识任务。",
    ),
    OperatorSpec(
        name="table_extract",
        stage="structure",
        layer="structure",
        status="planned",
        description="抽取表格块、表头和行列语义，形成表格 seed。",
        input_type="DocumentDTO",
        output_type="TableSeedListDTO",
        implementation_ref="kag.extractor.TableExtractor",
        applicable_sources=["report", "pdf", "document"],
        tags=["structure", "table", "seed"],
        decoupling_reason="表格解析是独立能力，后续可以服务指标抽取、事实抽取和证据绑定。",
    ),
    OperatorSpec(
        name="section_label",
        stage="structure",
        layer="structure",
        status="planned",
        description="为 chunk 打上章节或语义段标签，便于后续路由。",
        input_type="ChunkListDTO",
        output_type="ChunkListDTO",
        implementation_ref="planned:section-label-operator",
        applicable_sources=["report", "news", "document"],
        tags=["structure", "label", "chunk"],
        decoupling_reason="段落标签是中间结构增强，可被不同抽取算子共用。",
    ),
    OperatorSpec(
        name="entity_extract",
        stage="extract",
        layer="extract",
        status="planned",
        description="从 chunk 中抽取实体候选。",
        input_type="ChunkDTO",
        output_type="EntitySeedListDTO",
        implementation_ref="kag.extractor.SchemaConstraintExtractor.named_entity_recognition",
        applicable_sources=["news", "report", "document"],
        tags=["extract", "entity", "seed"],
        decoupling_reason="实体抽取是基础能力，可独立复用到问答、图谱和指标标注任务。",
        requires_llm=True,
        requires_schema=True,
    ),
    OperatorSpec(
        name="entity_standardize",
        stage="extract",
        layer="extract",
        status="planned",
        description="对实体候选做标准名归一、别名补充和官方名补齐。",
        input_type="EntitySeedListDTO",
        output_type="EntitySeedListDTO",
        implementation_ref="kag.extractor.SchemaConstraintExtractor.named_entity_standardization",
        applicable_sources=["news", "report", "document"],
        tags=["extract", "entity", "standardize"],
        decoupling_reason="标准化是实体抽取后的通用步骤，和关系/事件抽取可独立演进。",
        requires_llm=True,
        requires_schema=True,
    ),
    OperatorSpec(
        name="relation_extract",
        stage="extract",
        layer="extract",
        status="planned",
        description="从 chunk 与实体候选中抽取关系候选。",
        input_type="ChunkEntityBundleDTO",
        output_type="RelationSeedListDTO",
        implementation_ref="kag.extractor.SchemaConstraintExtractor.relations_extraction",
        applicable_sources=["news", "report", "document"],
        tags=["extract", "relation", "seed"],
        decoupling_reason="关系抽取的输入输出边界清晰，适合独立成可观测算子。",
        requires_llm=True,
        requires_schema=True,
    ),
    OperatorSpec(
        name="event_extract",
        stage="extract",
        layer="extract",
        status="planned",
        description="从 chunk 中抽取事件候选，包括主体、客体、时间和地点。",
        input_type="ChunkDTO",
        output_type="EventSeedListDTO",
        implementation_ref="kag.extractor.SchemaConstraintExtractor.event_extraction",
        applicable_sources=["news", "report", "document"],
        tags=["extract", "event", "seed"],
        decoupling_reason="事件抽取本身就是稳定职责边界，适合被资讯和研报两条链共同复用。",
        requires_llm=True,
        requires_schema=True,
    ),
    OperatorSpec(
        name="concept_seed_extract",
        stage="extract",
        layer="extract",
        status="planned",
        description="从文本中抽取行业、技术、企业分类等概念候选。",
        input_type="ChunkDTO",
        output_type="ConceptSeedListDTO",
        implementation_ref="planned:concept-seed-extractor",
        applicable_sources=["news", "report", "document"],
        tags=["extract", "concept", "seed"],
        decoupling_reason="概念候选抽取和最终概念绑定是两件事，前者适合独立成中间算子。",
        requires_llm=True,
        requires_schema=True,
    ),
    OperatorSpec(
        name="table_fact_extract",
        stage="extract",
        layer="extract",
        status="planned",
        description="从表格 seed 中抽取结构化事实和指标关系。",
        input_type="TableSeedListDTO",
        output_type="RelationSeedListDTO",
        implementation_ref="planned:table-fact-extractor",
        applicable_sources=["report", "pdf", "document"],
        tags=["extract", "table", "fact"],
        decoupling_reason="表格事实抽取是表格解析之后的独立能力，适合按指标规则单独迭代。",
    ),
    OperatorSpec(
        name="structured_entity_map",
        stage="mapping",
        layer="mapping",
        status="planned",
        description="把结构化实体行映射成图谱节点和属性。",
        input_type="StructuredRowDTO",
        output_type="GraphSeedDTO",
        implementation_ref="kag.mapping.SPGTypeMapping",
        applicable_sources=["fact_table", "ods", "csv"],
        tags=["mapping", "entity", "graph"],
        decoupling_reason="结构化映射只依赖字段到 schema 的映射规则，和抽取流程解耦。",
        requires_schema=True,
    ),
    OperatorSpec(
        name="structured_relation_map",
        stage="mapping",
        layer="mapping",
        status="planned",
        description="把结构化关系行映射成图谱边。",
        input_type="StructuredRelationRowDTO",
        output_type="GraphSeedDTO",
        implementation_ref="kag.mapping.SPOMapping",
        applicable_sources=["fact_table", "ods", "csv"],
        tags=["mapping", "relation", "graph"],
        decoupling_reason="关系表映射是通用图谱构建能力，可直接复用于常识层和外部事实层。",
        requires_schema=True,
    ),
    OperatorSpec(
        name="concept_hierarchy_map",
        stage="mapping",
        layer="mapping",
        status="planned",
        description="把概念表或概念候选映射成概念节点与 isA 层级。",
        input_type="ConceptSeedListDTO",
        output_type="GraphSeedDTO",
        implementation_ref="kag.mapping.SPGTypeMapping.hypernym_predicate",
        applicable_sources=["concept_seed", "taxonomy"],
        tags=["mapping", "concept", "hierarchy"],
        decoupling_reason="概念层级导入与实例抽取独立，适合单独管理和增量更新。",
        requires_schema=True,
    ),
    OperatorSpec(
        name="concept_bind",
        stage="resolve",
        layer="fusion",
        status="planned",
        description="把实体和事件挂到企业分类、行业、影响等概念层。",
        input_type="CanonicalKnowledgeBundleDTO",
        output_type="CanonicalKnowledgeBundleDTO",
        implementation_ref="app.incore_fusion_pipeline.mappers.concept_mapper.ConceptMapper",
        applicable_sources=["fact_table", "news", "report", "document"],
        tags=["fusion", "concept", "bind"],
        decoupling_reason="概念挂载是融合层的独立职责，和实体归一、落图都可分离演进。",
    ),
]


PIPELINE_TEMPLATES: List[Dict[str, object]] = [
    {
        "key": "news_event_pipeline",
        "name": "资讯事件链",
        "description": "面向资讯和快讯的事件抽取与融合闭环。",
        "source_types": ["news", "event"],
        "nodes": [
            {"key": "n1", "operator": "source_record_map", "title": "源记录映射", "lane": 0},
            {"key": "n2", "operator": "event_enrich", "title": "事件补全", "lane": 1},
            {"key": "n3", "operator": "entity_resolve", "title": "实体归一", "lane": 2},
            {"key": "n4", "operator": "event_resolve", "title": "事件归一", "lane": 3},
            {"key": "n5", "operator": "fusion_graph_build", "title": "融合建图", "lane": 4},
            {"key": "n6", "operator": "graph_import", "title": "导入 OpenSPG", "lane": 5},
        ],
        "edges": [
            {"from": "n1", "to": "n2"},
            {"from": "n2", "to": "n3"},
            {"from": "n3", "to": "n4"},
            {"from": "n4", "to": "n5"},
            {"from": "n5", "to": "n6"},
        ],
    },
    {
        "key": "report_extraction_pipeline",
        "name": "研报抽取链",
        "description": "面向研报文档的标准化、归一和落图模板。",
        "source_types": ["report", "document", "chunk", "event"],
        "nodes": [
            {"key": "r1", "operator": "source_record_map", "title": "文档/Chunk 映射", "lane": 0},
            {"key": "r2", "operator": "event_enrich", "title": "事件候选补全", "lane": 1},
            {"key": "r3", "operator": "entity_resolve", "title": "主体与区域归一", "lane": 2},
            {"key": "r4", "operator": "event_resolve", "title": "事件证据归一", "lane": 3},
            {"key": "r5", "operator": "fusion_graph_build", "title": "证据与知识建图", "lane": 4},
            {"key": "r6", "operator": "graph_import", "title": "导入 OpenSPG", "lane": 5},
        ],
        "edges": [
            {"from": "r1", "to": "r2"},
            {"from": "r2", "to": "r3"},
            {"from": "r3", "to": "r4"},
            {"from": "r4", "to": "r5"},
            {"from": "r5", "to": "r6"},
        ],
    },
    {
        "key": "structured_fusion_pipeline",
        "name": "结构化融合链",
        "description": "面向常识数据和结构化事实的标准融合模板。",
        "source_types": ["fact_table", "entity", "relation", "concept_seed"],
        "nodes": [
            {"key": "s1", "operator": "source_record_map", "title": "结构化记录映射", "lane": 0},
            {"key": "s2", "operator": "entity_resolve", "title": "实体归一与分类", "lane": 1},
            {"key": "s3", "operator": "event_resolve", "title": "事件归一", "lane": 2},
            {"key": "s4", "operator": "fusion_graph_build", "title": "概念/实体/关系建图", "lane": 3},
            {"key": "s5", "operator": "graph_import", "title": "导入 OpenSPG", "lane": 4},
        ],
        "edges": [
            {"from": "s1", "to": "s2"},
            {"from": "s2", "to": "s3"},
            {"from": "s3", "to": "s4"},
            {"from": "s4", "to": "s5"},
        ],
    },
    {
        "key": "pdf_report_full_pipeline",
        "name": "PDF 研报全链",
        "description": "从 PDF 接入开始，经过解析、切块和抽取形成可执行的研报抽取链。",
        "source_types": ["report", "pdf"],
        "nodes": [
            {"key": "p1", "operator": "pdf_source_ingest", "title": "PDF 接入", "lane": 0},
            {"key": "p2", "operator": "pdf_parse", "title": "PDF 解析", "lane": 1},
            {"key": "p3", "operator": "document_clean", "title": "文档清洗", "lane": 2},
            {"key": "p4", "operator": "chunk_split", "title": "切块", "lane": 3},
            {"key": "p5", "operator": "entity_extract", "title": "实体抽取", "lane": 4},
            {"key": "p6", "operator": "relation_extract", "title": "关系抽取", "lane": 5},
            {"key": "p7", "operator": "event_extract", "title": "事件抽取", "lane": 6},
            {"key": "p8", "operator": "concept_seed_extract", "title": "概念候选抽取", "lane": 7},
            {"key": "p9", "operator": "entity_standardize", "title": "实体标准化", "lane": 8},
        ],
        "edges": [
            {"from": "p1", "to": "p2"},
            {"from": "p2", "to": "p3"},
            {"from": "p3", "to": "p4"},
            {"from": "p4", "to": "p5"},
            {"from": "p5", "to": "p6"},
            {"from": "p6", "to": "p7"},
            {"from": "p7", "to": "p8"},
            {"from": "p8", "to": "p9"},
        ],
    },
    {
        "key": "web_news_full_pipeline",
        "name": "网页资讯全链",
        "description": "从网页资讯接入开始的清洗、切块和抽取可执行链路。",
        "source_types": ["news", "webpage", "url"],
        "nodes": [
            {"key": "w1", "operator": "webpage_source_ingest", "title": "网页接入", "lane": 0},
            {"key": "w2", "operator": "html_extract", "title": "正文抽取", "lane": 1},
            {"key": "w3", "operator": "document_clean", "title": "文档清洗", "lane": 2},
            {"key": "w4", "operator": "chunk_split", "title": "切块", "lane": 3},
            {"key": "w5", "operator": "entity_extract", "title": "实体抽取", "lane": 4},
            {"key": "w6", "operator": "relation_extract", "title": "关系抽取", "lane": 5},
            {"key": "w7", "operator": "event_extract", "title": "事件抽取", "lane": 6},
            {"key": "w8", "operator": "concept_seed_extract", "title": "概念候选抽取", "lane": 7},
            {"key": "w9", "operator": "entity_standardize", "title": "实体标准化", "lane": 8},
        ],
        "edges": [
            {"from": "w1", "to": "w2"},
            {"from": "w2", "to": "w3"},
            {"from": "w3", "to": "w4"},
            {"from": "w4", "to": "w5"},
            {"from": "w5", "to": "w6"},
            {"from": "w6", "to": "w7"},
            {"from": "w7", "to": "w8"},
            {"from": "w8", "to": "w9"},
        ],
    },
]
