from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Tuple


@dataclass(frozen=True)
class TableSpec:
    source_key: str
    output_name: str
    output_group: str
    entity_type: str
    keep_columns: Tuple[str, ...]
    filter_field: str
    filter_operator: str
    filter_value: Any
    filter_description: str
    text_fields: Tuple[str, ...] = ()
    name_field: str = "name"
    id_field: str = "id"
    export_columns: Tuple[str, ...] = ()


def _cols(*values: str) -> Tuple[str, ...]:
    return tuple(values)


QUICK_ENTITY_LIMITS = {
    "Company": 200,
    "Institution": 300,
    "Person": 800,
    "Project": 300,
    "Patent": 800,
    "Article": 300,
    "Achievement": 500,
    "Product": 200,
    "RankingList": 20,
}


ENTITY_SPECS: Tuple[TableSpec, ...] = (
    TableSpec(
        source_key="dw_company_info_tyc",
        output_name="company",
        output_group="entities",
        entity_type="Company",
        keep_columns=_cols(
            "id",
            "name",
            "used_name",
            "credit_code",
            "status",
            "establish_date",
            "province",
            "city",
            "regist_capi_value_cal",
            "insured_number",
            "website",
            "business_scope",
            "description",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "credit_code",
            "status",
            "establish_date",
            "province",
            "city",
            "website",
            "update_time",
        ),
        filter_field="status",
        filter_operator="in",
        filter_value=("存续", "在业", "正常"),
        filter_description="status in {存续, 在业, 正常}",
        text_fields=("business_scope", "description"),
    ),
    TableSpec(
        source_key="dw_institution_2026",
        output_name="institution",
        output_group="entities",
        entity_type="Institution",
        keep_columns=_cols(
            "id",
            "name",
            "support_org_id",
            "support_org_name",
            "type_1",
            "type_2",
            "domain",
            "province",
            "city",
            "website",
            "description",
            "level",
            "achievement",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "domain",
            "province",
            "city",
            "website",
            "level",
            "update_time",
        ),
        filter_field="domain",
        filter_operator="non_empty",
        filter_value=None,
        filter_description="domain is not empty",
        text_fields=("domain", "description", "achievement"),
    ),
    TableSpec(
        source_key="dw_investor",
        output_name="investor",
        output_group="entities",
        entity_type="Investor",
        keep_columns=_cols(
            "id",
            "name",
            "capital_scale",
            "total_invest_amount",
            "current_year_invest_amount",
            "next_round_ratio",
            "type",
            "intro",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "capital_scale",
            "total_invest_amount",
            "current_year_invest_amount",
            "type",
            "update_time",
        ),
        filter_field="total_invest_amount",
        filter_operator="ge_int",
        filter_value=5,
        filter_description="total_invest_amount >= 5",
        text_fields=("intro",),
    ),
    TableSpec(
        source_key="dw_expert",
        output_name="person",
        output_group="entities",
        entity_type="Person",
        keep_columns=_cols(
            "id",
            "name",
            "org",
            "orgs",
            "prof_title",
            "position",
            "research_fields",
            "honors",
            "awards",
            "resume",
            "province",
            "city",
            "url",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "org",
            "prof_title",
            "position",
            "research_fields",
            "province",
            "city",
            "update_time",
        ),
        filter_field="org",
        filter_operator="non_empty",
        filter_value=None,
        filter_description="org is not empty",
        text_fields=("research_fields", "honors", "awards", "resume"),
    ),
    TableSpec(
        source_key="dw_project",
        output_name="project",
        output_group="entities",
        entity_type="Project",
        keep_columns=_cols(
            "id",
            "name",
            "approval_num",
            "category",
            "approval_year",
            "project_leader",
            "org",
            "keywords",
            "abstract_zh",
            "funding_value",
            "start_date",
            "end_date",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "approval_num",
            "category",
            "approval_year",
            "funding_value",
            "start_date",
            "end_date",
            "update_time",
        ),
        filter_field="approval_year",
        filter_operator="ge_int",
        filter_value=2018,
        filter_description="approval_year >= 2018",
        text_fields=("keywords", "abstract_zh"),
    ),
    TableSpec(
        source_key="dw_patent_china",
        output_name="patent",
        output_group="entities",
        entity_type="Patent",
        keep_columns=_cols(
            "id",
            "title_cn",
            "title",
            "apply_code",
            "public_code",
            "patent_type",
            "grant_date",
            "apply_date",
            "public_date",
            "applicants_norm",
            "patentees_norm",
            "inventors",
            "main_ipc",
            "cited_other_times",
            "abstract_cn",
            "pdf_url",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "title_cn",
            "title",
            "apply_code",
            "public_code",
            "patent_type",
            "grant_date",
            "apply_date",
            "public_date",
            "main_ipc",
            "cited_other_times",
            "pdf_url",
            "update_time",
        ),
        filter_field="grant_date",
        filter_operator="non_empty",
        filter_value=None,
        filter_description="grant_date is not empty",
        text_fields=("abstract_cn",),
        name_field="title_cn",
    ),
    TableSpec(
        source_key="dw_article",
        output_name="article",
        output_group="entities",
        entity_type="Article",
        keep_columns=_cols(
            "id",
            "title",
            "abstract",
            "keywords",
            "authors",
            "year",
            "subject",
            "journal",
            "doi",
            "applicants",
            "url",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "title",
            "year",
            "subject",
            "journal",
            "doi",
            "url",
            "update_time",
        ),
        filter_field="year",
        filter_operator="ge_int",
        filter_value=2018,
        filter_description="year >= 2018",
        text_fields=("abstract", "keywords"),
        name_field="title",
    ),
    TableSpec(
        source_key="dw_achievement_info",
        output_name="achievement",
        output_group="entities",
        entity_type="Achievement",
        keep_columns=_cols(
            "id",
            "name",
            "type",
            "publish_time",
            "unit",
            "person",
            "technical_field",
            "application_field",
            "technology_maturity",
            "content",
            "url",
            "ipr",
            "honors",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "type",
            "publish_time",
            "technical_field",
            "application_field",
            "technology_maturity",
            "url",
            "update_time",
        ),
        filter_field="publish_time",
        filter_operator="date_ge",
        filter_value="2018-01-01",
        filter_description="publish_time >= 2018-01-01",
        text_fields=("technical_field", "application_field", "content", "ipr", "honors"),
    ),
    TableSpec(
        source_key="dw_standard_local",
        output_name="standard_local",
        output_group="entities",
        entity_type="StandardLocal",
        keep_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "local_name",
            "publish_date",
            "effective_date",
            "abolish_date",
            "industry_class",
            "standard_type",
            "publish_department",
            "drafting_unit",
            "status",
            "details",
            "url_link",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "local_name",
            "publish_date",
            "effective_date",
            "status",
            "url_link",
            "update_time",
        ),
        filter_field="abolish_date",
        filter_operator="empty",
        filter_value=None,
        filter_description="abolish_date is empty",
        text_fields=("details",),
        name_field="standard_name",
    ),
    TableSpec(
        source_key="dw_standard_industry",
        output_name="standard_industry",
        output_group="entities",
        entity_type="StandardIndustry",
        keep_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "domain_code",
            "domain_name",
            "publish_date",
            "effective_date",
            "abolish_date",
            "industry_class",
            "standard_type",
            "publish_department",
            "drafting_unit",
            "status",
            "details",
            "url_link",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "domain_code",
            "domain_name",
            "publish_date",
            "effective_date",
            "status",
            "url_link",
            "update_time",
        ),
        filter_field="status",
        filter_operator="eq",
        filter_value="现行",
        filter_description="status == 现行",
        text_fields=("details",),
        name_field="standard_name",
    ),
    TableSpec(
        source_key="dw_standard_nation",
        output_name="standard_nation",
        output_group="entities",
        entity_type="StandardNation",
        keep_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "publish_date",
            "effective_date",
            "abolish_date",
            "standard_type",
            "technical_unit",
            "effect_unit",
            "competent_department",
            "drafting_unit",
            "status",
            "details",
            "url_link",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "standard_code",
            "standard_name",
            "standard_level",
            "publish_date",
            "effective_date",
            "status",
            "url_link",
            "update_time",
        ),
        filter_field="status",
        filter_operator="eq",
        filter_value="现行",
        filter_description="status == 现行",
        text_fields=("details",),
        name_field="standard_name",
    ),
    TableSpec(
        source_key="dw_list",
        output_name="ranking_list",
        output_group="entities",
        entity_type="RankingList",
        keep_columns=_cols(
            "id",
            "name",
            "description",
            "publish_organization",
            "publish_time",
            "first_sort",
            "second_sort",
            "is_official",
            "indicator",
            "lz_industry_chain",
            "url",
            "update_time",
        ),
        export_columns=_cols(
            "id",
            "name",
            "publish_organization",
            "publish_time",
            "first_sort",
            "second_sort",
            "is_official",
            "url",
            "update_time",
        ),
        filter_field="is_official",
        filter_operator="eq",
        filter_value="1",
        filter_description="is_official == 1",
        text_fields=("description", "indicator"),
    ),
)


SUPPORT_SPECS: Tuple[TableSpec, ...] = (
    TableSpec(
        source_key="dw_company_main_product",
        output_name="company_main_product",
        output_group="support",
        entity_type="CompanyMainProduct",
        keep_columns=_cols("id", "name", "credit_code", "main_product", "update_time"),
        filter_field="main_product",
        filter_operator="non_empty",
        filter_value=None,
        filter_description="main_product is not empty",
        text_fields=("main_product",),
    ),
    TableSpec(
        source_key="dw_company_bidder",
        output_name="company_bidder",
        output_group="support",
        entity_type="CompanyBidder",
        keep_columns=_cols(
            "id",
            "title",
            "deal_money",
            "public_date",
            "tender",
            "bidder",
            "project_name",
            "industry",
            "project_address",
            "tender_type",
            "bidder_type",
            "update_time",
        ),
        filter_field="deal_money",
        filter_operator="gt_decimal",
        filter_value=0,
        filter_description="deal_money > 0",
        text_fields=("title", "project_name"),
        name_field="title",
    ),
    TableSpec(
        source_key="dw_list_detail",
        output_name="list_detail",
        output_group="support",
        entity_type="ListDetail",
        keep_columns=_cols(
            "id",
            "pid",
            "name",
            "sort_order",
            "cid",
            "company_name",
            "credit_code",
            "main_product",
            "industry",
            "indicator_value",
            "indicator_unit",
            "update_time",
        ),
        filter_field="sort_order",
        filter_operator="le_int",
        filter_value=100,
        filter_description="sort_order <= 100",
        text_fields=("main_product", "industry", "indicator_value"),
        name_field="company_name",
    ),
)


ALL_SPECS: Tuple[TableSpec, ...] = ENTITY_SPECS + SUPPORT_SPECS


def iter_specs() -> Iterable[TableSpec]:
    return ALL_SPECS
